language: python
install:
- pip install -r requirements.txt
script:
  - make artellapipe_repos
  - cd artellapipe_repos
  - git clone https://github.com/ArtellaPipe/artellapipe-utils.git
  - cd artellapipe-utils
  - sphinx-apidoc -f -e -o docs/sphinx artellapipe
  - travis-sphinx build --source=docs/sphinx  --nowarn
  - cd html
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
      branch: master