language: python
install:
- pip install -r requirements.txt
script:
  - pip install -r requirements.txt
  - mkdir artellapipe_repos
  - mkdir artellapipe_docs
  - cd artellapipe_repos
  - git clone https://github.com/ArtellaPipe/artellapipe-utils.git
  - git clone https://github.com/ArtellaPipe/artellapipe-gui.git
  - cd ..
  - sphinx-apidoc -f -e -o artellapipe_docs artellapipe_repos/artellapipe-utils/artellapipe --tocfile artellapipe-utils-modules
  - sphinx-apidoc -f -e -o artellapipe_docs artellapipe_repos/artellapipe-gui/artellapipe --tocfile artellapipe-gui-modules
  - sphinx-build -M html ./artellapipe_docs ./
  - cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: html
    on:
      branch: master