language: python
install:
- pip install -r requirements.txt
script:
  - pip install -r requirements.txt
  - mkdir artellapipe_repos
  - cd artellapipe_repos
  - git clone https://github.com/ArtellaPipe/artellapipe-utils.git
  - git clone https://github.com/ArtellaPipe/artellapipe-gui.git
  - cd ..
  - sphinx-apidoc -f -e -o artellapipe_repos/artellapipe-utils/docs/sphinx artellapipe_repos/artellapipe-utils/artellapipe
  - sphinx-apidoc -f -e -o artellapipe_repos/artellapipe-utils/docs/sphinx artellapipe_repos/artellapipe-gui/artellapipe
  - sphinx-build -M html ./artellapipe_repos/artellapipe-utils/docs/sphinx ./
  - sphinx-build -M html ./artellapipe_repos/artellapipe-gui/docs/sphinx ./
  - cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: html
    on:
      branch: master